System.argv()
|> hd()
|> File.stream!()
|> Stream.map(&String.trim/1)
|> Stream.map(&String.to_integer/1)
|> Stream.concat([0])
|> Enum.sort()
|> Enum.chunk_every(2, 1)
|> Stream.map(fn [a, b] -> b - a; [_] -> 3 end)
|> Enum.frequencies()
|> IO.inspect()
